// Data: List of products
const products = [
    // ----------------------------------------------------------INVT-----------------------------------------------------------
    {
        "id": "GD20-0R7G-S2-BK",
        "title": "Biến tần INVT GD20-0R7G-S2-BK 0.75kW 1 Pha 220V",
        "image": "Picture_Invt/GD20-0R7G-S2-BK.png",
        "sku": "GD20-0R7G-S2-BK",
        "manufacturer": "INVT",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_INVT/GD20 Series VFD Manual_V1.9.pdf",
        "price": "Liên hệ (0896 449 884)",
        // "infor_1":"",
        // "infor_2":"",
        "formPage": "Form_SP_INVT.html"
    },

    {
        "id": "GD20-1R5G-S2",
        "title": "Biến tần INVT GD20-1R5G-S2 1.5kW 1 Pha 220V",
        "image": "Picture_Invt/GD20-0R7G-S2-BK.png",
        "sku": "GD20-1R5G-S2",
        "manufacturer": "INVT",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_INVT/GD20 Series VFD Manual_V1.9.pdf",
        "price": "Liên hệ (0896 449 884)",
        // "infor_1":"",
        // "infor_2":"",
        "formPage": "Form_SP_INVT.html"
    },
    // ----------------------------------------------------------PLC S7-1200-----------------------------------------------------------
    {
        "id": "6ES7214-1AG40-0XB0",
        "title": "6ES7214-1AG40-0XB0 – Compact CPU 1214C DC/DC/DC S7-1200",
        "image": "Picture Siemens/S7-1200.png",
        "sku": "G6ES7214-1AG40-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/Catalogue_PLC_Siemens_S7_1200.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, CPU 1214C, COMPACT CPU, DC/DC/DC, ONBOARD I/O: 14 DI 24V DC; 10 DO 24 V DC; 2 AI 0 – 10V DC, POWER SUPPLY: DC 20.4 – 28.8 V DC, PROGRAM/DATA MEMORY: 100 KB.",
        "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
        "formPage": "Form_SP_Siemens.html"
    },
    {
        "id": "6ES7212-1AE40-0XB0",
        "title": "6ES7212-1AE40-0XB0 – Compact CPU 1212C DC/DC/DC S7-1200",
        "image": "Picture Siemens/S7-1200.png",
        "sku": "6ES7212-1AE40-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/Catalogue_PLC_Siemens_S7_1200.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, CPU 1212C, COMPACT CPU, DC/DC/DC, ONBOARD I/O: 8 DI 24V DC; 6 DO 24 V DC; 2 AI 0 – 10V DC, POWER SUPPLY: DC 20.4 – 28.8 V DC, PROGRAM/DATA MEMORY: 75 KB.",
        "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
        "formPage": "Form_SP_Siemens.html"
    },
    {
        "id": "6ES7211-1AE40-0XB0",
        "title": "6ES7211-1AE40-0XB0 – Compact CPU 1211C DC/DC/DC S7-1200",
        "image": "Picture Siemens/S7-1200.png",
        "sku": "6ES7211-1AE40-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/Catalogue_PLC_Siemens_S7_1200.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, CPU 1211C, COMPACT CPU, DC/DC/DC, ONBOARD I/O: 6 DI 24V DC; 4 DO 24 V DC; 2 AI 0 – 10V DC, POWER SUPPLY: DC 20.4 – 28.8 V DC, PROGRAM/DATA MEMORY: 50 KB",
        "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
        "formPage": "Form_SP_Siemens.html"
    },
    {
        "id": "6ES7211-1BE40-0XB0",
        "title": "6ES7211-1BE40-0XB0 – Compact CPU 1211C AC/DC/relay S7-1200",
        "image": "Picture Siemens/S7-1200.png",
        "sku": "6ES7211-1BE40-0XB0 ",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/Catalogue_PLC_Siemens_S7_1200.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, CPU 1211C, COMPACT CPU, AC/DC/RELAY, ONBOARD I/O: 6 DI 24V DC; 4 DO RELAY 2A; 2 AI 0 – 10V DC, POWER SUPPLY: AC 85 – 264 V AC AT 47 – 63 HZ, PROGRAM/DATA MEMORY: 50 KB",
        "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
        "formPage": "Form_SP_Siemens.html"
    },
    {
        "id": "6ES7214-1BG40-0XB0",
        "title": "6ES7214-1BG40-0XB0 – Compact CPU 1214C AC/DC/relay S7-1200",
        "image": "Picture Siemens/S7-1200.png",
        "sku": "6ES7214-1BG40-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/Catalogue_PLC_Siemens_S7_1200.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, CPU 1214C, COMPACT CPU, AC/DC/RLY, ONBOARD I/O: 14 DI 24V DC; 10 DO RELAY 2A; 2 AI 0 – 10V DC, POWER SUPPLY: AC 85 – 264 V AC AT 47 – 63 HZ, PROGRAM/DATA MEMORY: 100 KB.",
        "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
        "formPage": "Form_SP_Siemens.html"
    },
    {
        "id": "6ES7212-1HE40-0XB0",
        "title": "6ES7212-1HE40-0XB0 – Compact CPU 1214C DC/DC/DC S7-1200",
        "image": "Picture Siemens/S7-1200.png",
        "sku": "6ES7212-1HE40-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/Catalogue_PLC_Siemens_S7_1200.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, CPU 1212C, COMPACT CPU, DC/DC/RLY, ONBOARD I/O: 8 DI 24V DC; 6 DO RELAY 2A; 2 AI 0 – 10V DC, POWER SUPPLY: DC 20.4 – 28.8 V DC, PROGRAM/DATA MEMORY: 75 KB.",
        "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
        "formPage": "Form_SP_Siemens.html"
    },
    {
        "id": "6ES7212-1BE40-0XB0",
        "title": "6ES7212-1BE40-0XB0 – Compact CPU 1212C AC/DC/relay S7-1200",
        "image": "Picture Siemens/S7-1200.png",
        "sku": "6ES7212-1BE40-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/Catalogue_PLC_Siemens_S7_1200.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, CPU 1212C, COMPACT CPU, AC/DC/RLY, ONBOARD I/O: 8 DI 24V DC; 6 DO RELAY 2A; 2 AI 0 – 10V DC, POWER SUPPLY: AC 85 – 264 V AC AT 47 – 63 HZ, PROGRAM/DATA MEMORY: 75 KB.",
        "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
        "formPage": "Form_SP_Siemens.html"
    },
    {
        "id": "6ES7211-1HE40-0XB0",
        "title": "6ES7211-1HE40-0XB0 – Compact CPU 1211C DC/DC/relay S7-1200",
        "image": "Picture Siemens/S7-1200.png",
        "sku": "6ES7211-1HE40-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/Catalogue_PLC_Siemens_S7_1200.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, CPU 1211C, COMPACT CPU, DC/DC/RELAY, ONBOARD I/O: 6 DI 24V DC; 4 DO RELAY 2A; 2 AI 0 – 10V DC, POWER SUPPLY: DC 20.4 – 28.8 V DC, PROGRAM/DATA MEMORY: 50 KB.",
        "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
        "formPage": "Form_SP_Siemens.html"
    },
    {
        "id": "6ES7214-1HG40-0XB0",
        "title": "6ES7214-1HG40-0XB0 – Compact CPU 1214C DC/DC/relay S7-1200",
        "image": "Picture Siemens/S7-1200.png",
        "sku": "6ES7214-1HG40-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/Catalogue_PLC_Siemens_S7_1200.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, CPU 1214C, COMPACT CPU, DC/DC/RELAY, ONBOARD I/O: 14 DI 24V DC; 10 DO RELAY 2A; 2 AI 0 – 10V DC, POWER SUPPLY: DC 20.4 – 28.8 V DC, PROGRAM/DATA MEMORY: 100 KB.",
        "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
        "formPage": "Form_SP_Siemens.html"
    },
    {
        "id": "6ES7215-1AG40-0XB0",
        "title": "6ES7215-1AG40-0XB0 – Compact CPU 1215C DC/DC/DC S7-1200",
        "image": "Picture Siemens/S7-1215.png",
        "sku": "6ES7215-1AG40-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/Catalogue_PLC_Siemens_S7_1200.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, CPU 1215C, COMPACT CPU, DC/DC/DC, 2 PROFINET PORT, ONBOARD I/O: 14 DI 24V DC; 10 DO 24V DC 0.5A 2 AI 0-10V DC, 2 AO 0-20MA DC, POWER SUPPLY: DC 20.4 – 28.8 V DC, PROGRAM/DATA MEMORY: 125 KB.",
        "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
        "formPage": "Form_SP_Siemens.html"
    },
    {
        "id": "6ES7215-1BG40-0XB0",
        "title": "6ES7215-1BG40-0XB0 – Compact CPU 1215C AC/DC/relay S7-1200",
        "image": "Picture Siemens/S7-1215.png",
        "sku": "6ES7215-1BG40-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/Catalogue_PLC_Siemens_S7_1200.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, CPU 1215C, COMPACT CPU, AC/DC/RELAY, 2 PROFINET PORT, ONBOARD I/O: 14 DI 24V DC; 10 DO RELAY 2A, 2 AI 0-10V DC, 2 AO 0-20MA DC, POWER SUPPLY: AC 85 – 264 V AC AT 47 – 63 HZ, PROGRAM/DATA MEMORY: 125 KB.",
        "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
        "formPage": "Form_SP_Siemens.html"
    },
    {
        "id": "6ES7215-1HG40-0XB0",
        "title": "6ES7215-1HG40-0XB0 – Compact CPU 1215C DC/DC/relay S7-1200",
        "image": "Picture Siemens/S7-1215.png",
        "sku": "6ES7215-1HG40-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/Catalogue_PLC_Siemens_S7_1200.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, CPU 1215C, COMPACT CPU, DC/DC/RELAY, 2 PROFINET PORT, ONBOARD I/O: 14 DI 24V DC; 10 DO RELAY 2A, 2 AI 0-10V DC, 2 AO 0-20MA DC, POWER SUPPLY: DC 20.4 – 28.8 V DC, PROGRAM/DATA MEMORY: 125 KB.",
        "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
        "formPage": "Form_SP_Siemens.html"
    },
    {
        "id": "6ES7241-1CH30-1XB0",
        "title": "6ES7241-1CH30-1XB0 – Board truyền thông CB 1241 S7-1200",
        "image": "Picture Siemens/RS485.jpg",
        "sku": "6ES7241-1CH30-1XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/6ES72411CH301XB0_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, COMMUNICATION COMMUNICATION BOARD CB 1241, RS485, SCREW CONNECTOR SUPPORTS MESSAGE BASED FREEPORT.",
        // "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
        "formPage": "Form_SP_Siemns_Module.html"
    },
    {
        "id": "6ES7222-1BD30-0XB0",
        "title": "6ES7222-1BD30-0XB0 – Module SB 1222 4 DQ 24 VDC PLC S7-1200",
        "image": "Picture Siemens/SB-1222-digital-output-modules-4DQ-5VDC.png",
        "sku": "6ES7222-1BD30-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/6ES72221BD300XB0_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, DIGITAL OUTPUT SB 1222, 4DQ, 24VDC 200KHZ.",
        // "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
        "formPage": "Form_SP_Siemns_Module.html"
    },
    {
        "id": "6ES7232-4HA30-0XB0",
        "title": "6ES7232-4HA30-0XB0 – Module SB 1232 1AO SIMATIC S7-1200",
        "image": "Picture Siemens/6ES7232-4HA30-0XB0.jpg",
        "sku": "6ES7232-4HA30-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/6ES72324HA300XB0_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, ANALOG OUTPUT SB 1232, 1 AO, +/- 10VDC (12 BIT RES.) OR 0 – 20 MA (11 BIT RES).",
        // "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
        "formPage": "Form_SP_Siemns_Module.html"
    },
    {
        "id": "6ES7231-5PA30-0XB0",
        "title": "6ES7231-5PA30-0XB0 – Module SB 1231RTD 1 AI SIMATIC S7-1200",
        "image": "Picture Siemens/6ES7231-5PA30-0XB0.jpg",
        "sku": "6ES7231-5PA30-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/6ES72315PA300XB0_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, RTD INPUT, SB 1231 RTD, 1 AI RTD, 1 CHANNEL, PT 100 AND PT1000.",
        // "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
        "formPage": "Form_SP_Siemns_Module.html"
    },
    {
        "id": "6ES7223-3BD30-0XB0",
        "title": "6ES7223-3BD30-0XB0 – Module SB 1223 2 DI/2 DQ 24 VDC S7-1200",
        "image": "Picture Siemens/6ES7223-3BD30-0XB0.jpg",
        "sku": "6ES7223-3BD30-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/6ES72233BD300XB0_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, DIGITAL I/O SB 1223, 2DI/2DQ, 24VDC 200KHZ.",
        // "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
        "formPage": "Form_SP_Siemns_Module.html"
    },
    {
        "id": "6ES7222-1AD30-0XB0",
        "title": "6ES7222-1AD30-0XB0 – Module Digital output SB 1222 4 DQ S7-1200",
        "image": "Picture Siemens/6ES7222-1AD30-0XB0.jpg",
        "sku": "6ES7222-1AD30-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/6ES72221AD300XB0_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, DIGITAL OUTPUT SB 1222, 4DQ, 5VDC 200KHZ.",
        // "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
        "formPage": "Form_SP_Siemns_Module.html"
    },
    {
        "id": "6ES7954-8LC03-0AA0",
        "title": "6ES7954-8LC03-0AA0 – Thẻ nhớ cho S7-1×00 CPU/ Sinamics 4MB",
        "image": "Picture Siemens/6ES7954-8LC03-0AA0.jpg",
        "sku": "6ES7954-8LC03-0AA0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/6ES79548LC030AA0_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7, MEMORY CARD FOR S7-1X00 CPU/SINAMICS, 3,3 V FLASH, 4 MBYTE.",
        // "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
        "formPage": "Form_SP_Siemns_Module.html"
    },
    {
        "id": "6ES7954-8LC02-0AA0",
        "title": "6ES7954-8LC02-0AA0 – Thẻ nhớ cho S7-1×00 CPU/ Sinamics 4MB",
        "image": "Picture Siemens/6ES7954-8LC02-0AA0.jpg",
        "sku": "6ES7954-8LC02-0AA0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/6ES79548LC020AA0_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7, MEMORY CARD FOR S7-1X00 CPU/SINAMICS, 3,3 V FLASH, 4 MBYTE.",
        // "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
        "formPage": "Form_SP_Siemns_Module.html"
    },

    // -----------------------------------------------------S7-1500------------------------------------------------------------
    {
        "id": "6ES7590-1AB60-0AA0",
        "title": "6ES7590-1AB60-0AA0 rail 160mm S7-1500",
        "image": "Picture Siemens/6ES7590-1AB60-0AA0.jpg",
        "sku": "6ES7590-1AB60-0AA0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/6ES75901AB600AA0_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1500, thanh ray gắn 160 mm (khoảng 6.3 inch); bao gồm ốc nối đất, ray DIN tích hợp để lắp đặt các phụ kiện như đầu nối, cầu chì tự động và rơ le.",
        "formPage": "Form_SP_Siemns_S7_1500.html"
    },
    {
        "id": "6ES7513-1AL02-0AB0",
        "title": "6ES7513-1AL02-0AB0 Bộ Lập Trình CPU 1513-1 PN",
        "image": "Picture Siemens/6ES7513-1AL02-0AB0.jpg",
        "sku": "6ES7513-1AL02-0AB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/6ES75131AL020AB0_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1500, CPU 1513-1 PN, là bộ xử lý trung tâm với bộ nhớ làm việc 300 KB cho chương trình và 1,5 MB cho dữ liệu, tích hợp giao diện PROFINET IRT với switch 2 cổng, hiệu suất bit 40 ns. Bộ nhớ SIMATIC là cần thiết..",
        "infor_2":"SIMATIC S7-1500 là dòng PLC tiên tiến của Siemens, được sử dụng trong các hệ thống tự động hóa công nghiệp, nổi bật với khả năng xử lý nhanh, độ tin cậy cao và tính linh hoạt.<br>CPU 1513-1 PN thuộc dòng CPU hiệu suất cao, phù hợp cho các ứng dụng điều khiển yêu cầu độ chính xác và thời gian thực nhanh, như trong các hệ thống tự động hóa nhà máy hoặc dây chuyền sản xuất.<br>PROFINET IRT (Isochronous Real Time) là giao thức mạng tiên tiến, hỗ trợ truyền dữ liệu với độ trễ rất thấp, giúp tăng hiệu quả và khả năng điều khiển trong các ứng dụng công nghiệp đòi hỏi thời gian thực.",
        "formPage": "Form_SP_Siemns_S7_1500.html"
    },
    {
        "id": "6ES7531-7KF00-0AB0",
        "title": "6ES7531-7KF00-0AB0 S7-1500 SM 531 8AI",
        "image": "Picture Siemens/6ES7531-7KF00-0AB0.jpg",
        "sku": "6ES7531-7KF00-0AB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/6ES75317KF000AB0_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"AI 8 X U/I/RTD/TC ST thuộc dòng SIMATIC S7-1500, có độ phân giải 16 bit và độ chính xác 0,3%. Nó hỗ trợ 8 kênh đầu vào, với các nhóm 8 kênh, trong đó có 4 kênh đo RTD (Resistance Temperature Detector). Module này cũng có khả năng chẩn đoán và báo động quy trình, có điện áp chế độ chung xấp xỉ 10V. Kèm theo là các phụ kiện bao gồm bộ kẹp chắn và kẹp che chắn.",
        "formPage": "Form_SP_Siemns_S7_1500.html"
    },
    {
        "id": "6ES7532-5HF00-0AB0",
        "title": "6ES7532-5HF00-0AB0 S7-1500 SM 532 8AO",
        "image": "Picture Siemens/6ES7532-5HF00-0AB0.jpg",
        "sku": "6ES7532-5HF00-0AB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/6ES75325HF000AB0_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Bộ module đầu ra analog AQ 8 X U/I HS thuộc dòng SIMATIC S7-1500. Nó có độ phân giải 16 bit và độ chính xác 0,3%, với 8 kênh đầu ra được nhóm thành các nhóm 8 kênh. Tính năng chẩn đoán và giá trị thay thế cũng được tích hợp, có thể xử lý 8 kênh trong thời gian 0,125 ms. Sản phẩm này bao gồm cả các phụ kiện như bộ kẹp chắn, kẹp che chắn, và thành phần cấp nguồn.",
        "formPage": "Form_SP_Siemns_S7_1500.html"
    },
    {
        "id": "6ES7511-1AK02-0AB0",
        "title": "6ES7511-1AK02-0AB0 S7-1500 CPU 1511-1 PN",
        "image": "Picture Siemens/6ES7532-5HF00-0AB0.jpg",
        "sku": "6ES7511-1AK02-0AB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/6ES75111AK020AB0_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Bộ module đầu ra analog AQ 8 X U/I HS thuộc dòng SIMATIC S7-1500. Nó có độ phân giải 16 bit và độ chính xác 0,3%, với 8 kênh đầu ra được nhóm thành các nhóm 8 kênh. Tính năng chẩn đoán và giá trị thay thế cũng được tích hợp, có thể xử lý 8 kênh trong thời gian 0,125 ms. Sản phẩm này bao gồm cả các phụ kiện như bộ kẹp chắn, kẹp che chắn, và thành phần cấp nguồn.",
        "formPage": "Form_SP_Siemns_S7_1500.html"
    },
    // ------------------------------------------------------HMI----------------------------------------------------------------
    {
        "id": "6AV2124-0MC01-0AX0",
        "title": "6AV2124-0MC01-0AX0 – Màn hình HMI Comford TP1200 12″",
        "image": "Picture Siemens/6AV2124-0MC01-0AX0.jpg",
        "sku": "6AV2124-0MC01-0AX0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/6AV21240MC010AX0_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC HMI TP1200 Comfort, Bảng điều khiển tiện nghi, thao tác bằng cảm ứng, màn hình TFT màn hình rộng 12 inch, 16 triệu màu, giao diện PROFINET, giao diện MPI/PROFIBUS DP, bộ nhớ cấu hình 12 MB, Windows CE 6.0, có thể cấu hình từ WinCC Comfort V11." ,
        "formPage": "Form_SP_Siemns_HMI.html"
    },
    {
        "id": "6AV2123-2GB03-0AX0",
        "title": "6AV2123-2GB03-0AX0 – Màn hình HMI Basic KTP 700 7″",
        "image": "Picture Siemens/6AV2123-2GB03-0AX0.jpg",
        "sku": "6AV2123-2GB03-0AX0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/6AV21232GB030AX0_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC HMI, KTP700 Basic, Bảng điều khiển cơ bản, Thao tác phím/chạm, màn hình TFT 7 inch, 65536 màu, giao diện PROFINET, có thể cấu hình từ WinCC Basic V13/ STEP 7 Basic V13, chứa phần mềm nguồn mở, được cung cấp miễn phí, xem kèm theo đĩa CD." ,
        "formPage": "Form_SP_Siemns_HMI.html"
    },
    {
        "id": "6AV2124-0QC02-0AX1",
        "title": "6AV2124-0QC02-0AX1 – Màn hình HMI Comford TP1500 15″",
        "image": "Picture Siemens/6AV2124-0QC02-0AX1.jpg",
        "sku": "6AV2124-0QC02-0AX1",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/6AV21240QC020AX1_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC HMI, KTP700 Basic, Bảng điều khiển cơ bản, Thao tác phím/chạm, màn hình TFT 7 inch, 65536 màu, giao diện PROFINET, có thể cấu hình từ WinCC Basic V13/ STEP 7 Basic V13, chứa phần mềm nguồn mở, được cung cấp miễn phí, xem kèm theo đĩa CD." ,
        "formPage": "Form_SP_Siemns_HMI.html"
    },
    // -----------------------------------------------------ET200--------------------------------------------------------------
    {
        "id": "6ES7137-6AA00-0BA0",
        "title": "6ES7137-6AA00-0BA0 – Module truyền thông CM PTP ET 200SP",
        "image": "Picture Siemens/6ES7137-6AA00-0BA0.jpg",
        "sku": "6ES7137-6AA00-0BA0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/6ES71376AA000BA0_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC ET 200SP, mô-đun giao tiếp CM PTP cho kết nối nối tiếp RS422, RS485 và RS232, Freeport, 3964 (R), USS, MODBUS RTU Master, Slave, 115200 Kbit/s." ,
        "formPage": "Form_SP_Siemns_ET200.html"
    },
    // ---------------------------------------------Safety Control Devices------------------------------------------------------
    {
        "id": "3TK2825-1BB40",
        "title": "Thiết bị an toàn Sirius (Sirius Safety) Siemens 3TK2825-1BB40",
        "image": "Picture Siemens/3TK2825-1BB40.jpg",
        "sku": "3TK2825-1BB40",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/3TK28251BB40_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Rơle an toàn SIRIUS với mạch kích hoạt rơle (EC) 24 VDC, chiều rộng tổng thể 45 mm Thiết bị đầu cuối trục vít EC tức thời: 3 NO EC bị trễ: 0 NO SC: 2 NC Tự động khởi động/khởi động được giám sát Thiết bị cơ bản SIL đạt được tối đa: 3, PL: E." ,
        "formPage": "Form_SP_Siemns_Safety.html"
    },
    // -----------------------------------------------------SITOP---------------------------------------------------------------
    {
        "id": "6EP1331-5BA10",
        "title": "6EP1331-5BA10 – Stabilized Power Supply SITOP PSU100C 24 V/1.3 A",
        "image": "Picture Siemens/6EP1331-5BA10.jpg",
        "sku": "6EP1331-5BA10",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/6EP13315BA10_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SITOP PSU100C 24 V/1.3 A đầu vào nguồn điện ổn định: 120-230 VAC (110-300 V DC) đầu ra: 24 VDC/1.3 A." ,
        "formPage": "Form_SP_Siemns_SITOP.html"
    },
    {
        "id": "6EP1332-2BA20",
        "title": "6EP1332-2BA20 – Stabilized Power Supply SITOP PSU100S 24 V/2.5 A",
        "image": "Picture Siemens/6EP1332-2BA20.jpg",
        "sku": "6EP1332-2BA20",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/6EP13322BA20_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SITOP PSU100S 24 V/2.5 A Đầu vào nguồn điện ổn định: 120/230 VAC Đầu ra: 24 VDC/2.5 A." ,
        "formPage": "Form_SP_Siemns_SITOP.html"
    },
    // -----------------------------------------------------CB Scheider--------------------------------------------------------
    {
        "id": "EZ9F34240",
        "title": "MCB Schneider EZ9F34240 40A 4.5kA 2P",
        "image": "Picture Schneider/EZ9F34240.jpg",
        "sku": "EZ9F34240",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Easy9-MCBs_EZ9F34240.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Bảo vệ chống dòng quá tải<br>Bảo vệ chống dòng ngắn mạch<br>Số cực: 2P<br>Dòng điện định mức: 40A<br>Dòng cắt ngắn mạch: 4.5kA<br>Điện áp định mức: 230V" ,
        "formPage": "Form_SP_Schneider_PD.html"
    },
    {
        "id": "EZ9F34220",
        "title": "MCB Schneider EZ9F34220 20A 4.5kA 2P",
        "image": "Picture Schneider/EZ9F34240.jpg",
        "sku": "EZ9F34220",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Easy9-MCBs_EZ9F34220.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Bảo vệ chống dòng quá tải<br>Bảo vệ chống dòng ngắn mạch<br>Số cực: 2P<br>Dòng điện định mức: 20A<br>Dòng cắt ngắn mạch: 4.5kA<br>Điện áp định mức: 230V" ,
        "formPage": "Form_SP_Schneider_PD.html"
    },
    {
        "id": "EZ9F34232",
        "title": "MCB Schneider EZ9F34232 32A 4.5kA 2P",
        "image": "Picture Schneider/EZ9F34240.jpg",
        "sku": "EZ9F34232",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Easy9-MCBs_EZ9F34232.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Bảo vệ chống dòng quá tải<br>Bảo vệ chống dòng ngắn mạch<br>Số cực: 2P<br>Dòng điện định mức: 32A<br>Dòng cắt ngắn mạch: 4.5kA<br>Điện áp định mức: 230V" ,
        "formPage": "Form_SP_Schneider_PD.html"
    },
    {
        "id": "EZ9F34210",
        "title": "MCB Schneider EZ9F34210 10A 4.5kA 2P",
        "image": "Picture Schneider/EZ9F34240.jpg",
        "sku": "EZ9F34210",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Easy9-MCBs_EZ9F34210.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Bảo vệ chống dòng quá tải<br>Bảo vệ chống dòng ngắn mạch<br>Số cực: 2P<br>Dòng điện định mức: 10A<br>Dòng cắt ngắn mạch: 4.5kA<br>Điện áp định mức: 230V" ,
        "formPage": "Form_SP_Schneider_PD.html"
    },
    {
        "id": "A9F74232",
        "title": "MCB Schneider A9F74232 32A 6kA 2P  ",
        "image": "Picture Schneider/A9F74232.JPG",
        "sku": "A9F74232",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Acti-9-iC60_A9F74232.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Số cực: 2P<br>Dòng điện định mức: 32A<br>Dòng cắt ngắn mạch: 6kA<br>Điện áp định mức: 230V" ,
        "formPage": "Form_SP_Schneider_PD.html"
    },
    {
        "id": "A9K27220",
        "title": "MCB Schneider A9K27220 20A 6kA 2P",
        "image": "Picture Schneider/A9F74232.JPG",
        "sku": "A9K27220",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Acti-9-iK60_A9K27220.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Số cực: 2P<br>Dòng điện định mức: 20A<br>Dòng cắt ngắn mạch: 6kA<br>Điện áp định mức: 230V" ,
        "formPage": "Form_SP_Schneider_PD.html"
    },
    {
        "id": "A9F74216",
        "title": "MCB Schneider A9F74216 16A 6kA 2P ",
        "image": "Picture Schneider/A9F74232.JPG",
        "sku": "A9F74216",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Acti-9-iC60_A9F74216.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Số cực: 2P<br>Dòng điện định mức: 16A<br>Dòng cắt ngắn mạch: 6kA<br>Điện áp định mức: 230V" ,
        "formPage": "Form_SP_Schneider_PD.html"
    },
    {
        "id": "A9F74210",
        "title": "MCB Schneider A9F74210 10A 6kA 2P",
        "image": "Picture Schneider/A9F74232.JPG",
        "sku": "A9F74210",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Acti-9-iC60_A9F74210.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Số cực: 2P<br>Dòng điện định mức: 10A<br>Dòng cắt ngắn mạch: 6kA<br>Điện áp định mức: 230V" ,
        "formPage": "Form_SP_Schneider_PD.html"
    },
    {
        "id": "EZ9F34332",
        "title": "MCB Schneider EZ9F34332 32A 4.5kA 3P",
        "image": "Picture Schneider/EZ9F34332.JPG",
        "sku": "EZ9F34332",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Easy9-MCBs_EZ9F34332.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Bảo vệ chống dòng quá tải<br>Bảo vệ chống dòng ngắn mạch<br>Số cực: 3P<br>Dòng điện định mức: 32A<br>Dòng cắt ngắn mạch: 4.5kA<br>Điện áp định mức: 400V" ,
        "formPage": "Form_SP_Schneider_PD.html"
    },
    {
        "id": "EZ9F34306",
        "title": "MCB Schneider EZ9F34306 6A 4.5kA 3P",
        "image": "Picture Schneider/EZ9F34332.JPG",
        "sku": "EZ9F34306",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Easy9-MCBs_EZ9F34306.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Bảo vệ chống dòng quá tải<br>Bảo vệ chống dòng ngắn mạch<br>Số cực: 3P<br>Dòng điện định mức: 6A<br>Dòng cắt ngắn mạch: 4.5kA<br>Điện áp định mức: 400V" ,
        "formPage": "Form_SP_Schneider_PD.html"
    },
    {
        "id": "EZ9F34340",
        "title": "MCB Schneider EZ9F34340 40A 4.5kA 3P",
        "image": "Picture Schneider/EZ9F34332.JPG",
        "sku": "EZ9F34340",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Easy9-MCBs_EZ9F34340.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Bảo vệ chống dòng quá tải<br>Bảo vệ chống dòng ngắn mạch<br>Số cực: 3P<br>Dòng điện định mức: 40A<br>Dòng cắt ngắn mạch: 4.5kA<br>Điện áp định mức: 400V" ,
        "formPage": "Form_SP_Schneider_PD.html"
    },
    {
        "id": "EZ9F34320",
        "title": "MCB Schneider EZ9F34320 20A 4.5kA 3P",
        "image": "Picture Schneider/EZ9F34332.JPG",
        "sku": "EZ9F34320",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Easy9-MCBs_EZ9F34320.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Bảo vệ chống dòng quá tải<br>Bảo vệ chống dòng ngắn mạch<br>Số cực: 3P<br>Dòng điện định mức: 20A<br>Dòng cắt ngắn mạch: 4.5kA<br>Điện áp định mức: 400V" ,
        "formPage": "Form_SP_Schneider_PD.html"
    },
    {
        "id": "A9F74332",
        "title": "MCB Schneider A9F74332 32A 6kA 3P",
        "image": "Picture Schneider/A9F74332.JPG",
        "sku": "A9F74332",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Acti-9-iC60_A9F74332.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Số cực: 3P<br>Dòng điện định mức: 32A<br>Dòng cắt ngắn mạch: 6kA<br>Điện áp định mức: 400V" ,
        "formPage": "Form_SP_Schneider_PD.html"
    },
    {
        "id": "A9F74340",
        "title": "MCB Schneider A9F74340 40A 6kA 3P",
        "image": "Picture Schneider/A9F74332.JPG",
        "sku": "A9F74340",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Acti-9-iC60_A9F74340.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Số cực: 3P<br>Dòng điện định mức: 40A<br>Dòng cắt ngắn mạch: 6kA<br>Điện áp định mức: 400V" ,
        "formPage": "Form_SP_Schneider_PD.html"
    },
    {
        "id": "A9F74310",
        "title": "MCB Schneider A9F74310 10A 6kA 3P",
        "image": "Picture Schneider/A9F74332.JPG",
        "sku": "A9F74310",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Acti-9-iC60_A9F74310.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Số cực: 3P<br>Dòng điện định mức: 10A<br>Dòng cắt ngắn mạch: 6kA<br>Điện áp định mức: 400V" ,
        "formPage": "Form_SP_Schneider_PD.html"
    },
    {
        "id": "EZC100N3075",
        "title": "MCCB Schneider EZC100N3075 75A 15kA 3P",
        "image": "Picture Schneider/EZC100N3075.JPG",
        "sku": "EZC100N3075",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_EasyPact-EZC_EZC100N3075.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Số cực: 3P<br>Dòng điện định mức: 75A<br>Dòng cắt ngắn mạch: 15kA<br>Điện áp định mức: 415V" ,
        "formPage": "Form_SP_Schneider_PD.html"
    },
    {
        "id": "EZC100F3100",
        "title": "MCCB Schneider EZC100F3100 100A 10kA 3P",
        "image": "Picture Schneider/EZC100N3075.JPG",
        "sku": "EZC100F3100",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_EasyPact-EZC_EZC100F3100.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Số cực: 3P<br>Dòng điện định mức: 100A<br>Dòng cắt ngắn mạch: 10kA<br>Điện áp định mức: 415V" ,
        "formPage": "Form_SP_Schneider_PD.html"
    },
    {
        "id": "EZC250N3100",
        "title": "MCCB Schneider EZC250N3100 100A 25kA 3P",
        "image": "Picture Schneider/EZC250N3100.JPG",
        "sku": "EZC250N3100",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_EasyPact-EZC_EZC250N3100.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Số cực: 3P<br>Dòng điện định mức: 100A<br>Dòng cắt ngắn mạch: 25kA<br>Điện áp định mức: 415V" ,
        "formPage": "Form_SP_Schneider_PD.html"
    },
    {
        "id": "EZC100N3100",
        "title": "MCCB Schneider EZC100N3100 100A 15kA 3P",
        "image": "Picture Schneider/EZC100N3075.JPG",
        "sku": "EZC100N3100",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_EasyPact-EZC_EZC100N3100.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Số cực: 3P<br>Dòng điện định mức: 100A<br>Dòng cắt ngắn mạch: 15kA<br>Điện áp định mức: 415V" ,
        "formPage": "Form_SP_Schneider_PD.html"
    },
    {
        "id": "EZ9L33620",
        "title": "CB chống sét Schneider EZ9L33620 20kA 1P+N",
        "image": "Picture Schneider/EZ9L33620.JPG",
        "sku": "EZ9L33620",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Easy9_EZ9L33620.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Hệ thống đường truyền tín hiệu là một trong những mục tiêu của sét và có đến 75% các đường truyền tín hiệu hỏng hóc do bị sét đánh. Do đó, để bảo vệ đường truyền liên lạc không bị đứt quãng, nên sử dụng thiết bị CB chống sét Schneider EZ9L33620 20kA 1P+N được dùng để cắt sét, dẫn năng lượng sét xuống đất và giảm biên độ sung sét, đồng thời làm giảm áp lực của sét đến nguồn điện và thiết bị điện sẽ đảm bảo an toàn cho cả hệ thống điện gia đình, hoặc chọn thiết bị chống sét cho từng thiết bị điện công nghiệp như: cửa cuốn, tivi, điện thoại, máy tính…" ,
        "infor_2":"Loại: Chống Sét Lan Truyền Nguồn TT, TN-S <br> Dòng Sản Phẩm: Easy 9 <br> Kiểu: Type 2 <br> Công Nghệ Cắt Lọc Sét: MOV + GDT <br> Số Cực: 1P + N <br> Điện Áp: 230V AC <br> Dòng Cắt Sét In: 10 KA <br> Dòng Cắt Sét Imax: 20 KA <br> Kiểu Lắp Đặt: Gắn Thanh DIN Rail 35mm <br> Tiêu Chuẩn: IEC",
        "formPage": "Form_SP_Schneider_PD.html"
    },
    {
        "id": "EZ9L33745",
        "title": "CB chống sét Schneider EZ9L33745 45kA 3P+N",
        "image": "Picture Schneider/EZ9L33745.JPG",
        "sku": "EZ9L33745",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Easy9_EZ9L33745.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Hệ thống đường truyền tín hiệu là một trong những mục tiêu của sét và có đến 75% các đường truyền tín hiệu hỏng hóc do bị sét đánh. Do đó, để bảo vệ đường truyền liên lạc không bị đứt quãng, nên sử dụng thiết bị CB chống sét Schneider EZ9L33745 45kA 3P+N được dùng để cắt sét, dẫn năng lượng sét xuống đất và giảm biên độ sung sét, đồng thời làm giảm áp lực của sét đến nguồn điện và thiết bị điện sẽ đảm bảo an toàn cho cả hệ thống điện gia đình, hoặc chọn thiết bị chống sét cho từng thiết bị điện công nghiệp như: cửa cuốn, tivi, điện thoại, máy tính…" ,
        "infor_2":"Loại: Chống Sét Lan Truyền Nguồn TT, TN-S <br> Dòng Sản Phẩm: Easy 9 <br> Kiểu: Type 2 <br> Công Nghệ Cắt Lọc Sét: MOV + GDT <br> Số Cực: 3P + N <br> Điện Áp: 230V AC <br> Dòng Cắt Sét In: 20 KA <br> Dòng Cắt Sét Imax: 45 KA <br> Kiểu Lắp Đặt: Gắn Thanh DIN Rail 35mm <br> Tiêu Chuẩn: IEC",
        "formPage": "Form_SP_Schneider_PD.html"
    },
    // --------------------------------------------------Button-------------------------------------------------------------------
    {
        "id": "XA2EA31",
        "title": "Nút nhấn nhả Schneider XA2EA31, 22mm",
        "image": "Picture Schneider/XA2EA31.JPG",
        "sku": "XA2EA31",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Easy-Harmony-XA2_XA2EA31.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Tiếp điểm: N/O <br> Màu: Xanh lá cây <br> Đường kính: 22mm" ,
        "formPage": "Form_SP_Schneider_AT.html"
    },
    {
        "id": "XA2EA42",
        "title": "Nút nhấn nhả Schneider XA2EA42, 22mm",
        "image": "Picture Schneider/XA2EA42.JPG",
        "sku": "XA2EA42",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Easy-Harmony-XA2_XA2EA42.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Tiếp điểm: N/C <br> Màu: Xanh đỏ <br> Đường kính: 22mm" ,
        "formPage": "Form_SP_Schneider_AT.html"
    },
    {
        "id": "XA2ED21",
        "title": "Công tắc xoay 2 vị trí Schneider XA2ED21, 22mm (tự giữ)",
        "image": "Picture Schneider/XA2ED21.JPG",
        "sku": "XA2ED21",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Easy-Harmony-XA2_XA2ED21.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Tiếp điểm: N/O <br> Số vị trí: 2 vị trí - tự giữ <br> Đường kính: 22mm" ,
        "formPage": "Form_SP_Schneider_AT.html"
    },
    {
        "id": "XA2ED33",
        "title": "Công tắc xoay 3 vị trí Schneider XA2ED33, 22mm (tự giữ)",
        "image": "Picture Schneider/XA2ED33.JPG",
        "sku": "XA2ED33",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Easy-Harmony-XA2_XA2ED33.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Tiếp điểm: 2N/O <br> Số vị trí: 3 vị trí - tự giữ <br> Đường kính: 22mm" ,
        "formPage": "Form_SP_Schneider_AT.html"
    },
    {
        "id": "XA2ET42",
        "title": "Nút dừng khẩn cấp Schneider XA2ET42, 22mm",
        "image": "Picture Schneider/XA2ET42.JPG",
        "sku": "XA2ET42",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Easy-Harmony-XA2_XA2ET42.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":" Tiếp điểm: N/C . <br>Đường kính: Ø40 – red <br>Cách tác động: Nhấn-kéo nhả" ,
        "formPage": "Form_SP_Schneider_Safety.html"
    },
    // ---------------------------------------------------Light---------------------------------------------------------------
    {
        "id": "XA2ED33",
        "title": "Công tắc xoay 3 vị trí Schneider XA2ED33, 22mm (tự giữ)",
        "image": "Picture Schneider/XA2EVM4LC.JPG",
        "sku": "XA2ED33",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Easy-Harmony-XA2_XA2EVM4LC.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Màu: Đỏ <br> Đường kính: 22mm" ,
        "formPage": "Form_SP_Schneider_Safety.html"
    },
    {
        "id": "XA2EVM3LC",
        "title": "Đèn báo Schneider XA2EVM3LC, 22mm 220V AC",
        "image": "Picture Schneider/XA2EVM3LC.JPG",
        "sku": "XA2EVM3LC",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Easy-Harmony-XA2_XA2EVM3LC.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Màu: Xanh <br> Đường kính: 22mm" ,
        "formPage": "Form_SP_Schneider_Safety.html"
    },
    {
        "id": "XA2EVM5LC",
        "title": "Đèn báo Schneider XA2EVM5LC, 22mm 220V AC",
        "image": "Picture Schneider/XA2EVM5LC.JPG",
        "sku": "XA2EVM5LC",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Easy-Harmony-XA2_XA2EVM5LC.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Màu: Vàng <br> Đường kính: 22mm" ,
        "formPage": "Form_SP_Schneider_Safety.html"
    },
    {
        "id": "XA2EVB3LC",
        "title": "Đèn báo Schneider XA2EVB3LC, 22mm 24V AC/DC",
        "image": "Picture Schneider/XA2EVB3LC.JPG",
        "sku": "XA2EVB3LC",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Easy-Harmony-XA2_XA2EVB3LC.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Màu: Xanh <br> Đường kính: 22mm" ,
        "formPage": "Form_SP_Schneider_Safety.html"
    },
    {
        "id": "XA2EVB4LC",
        "title": "Đèn báo Schneider XA2EVB4LC, 22mm 24V AC/DC",
        "image": "Picture Schneider/XA2EVM4LC.JPG",
        "sku": "XA2EVB4LC",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Easy-Harmony-XA2_XA2EVB4LC.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Màu: Đỏ <br> Đường kính: 22mm" ,
        "formPage": "Form_SP_Schneider_Safety.html"
    },
    {
        "id": "XB7NA31",
        "title": "Nút nhấn nhả Schneider XB7NA31, 22mm",
        "image": "Picture Schneider/XB7NA31.JPG",
        "sku": "XB7NA31",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Harmony-XB7_XB7NA31.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Tiếp điểm: N/O <br> Màu: Xanh là cây <br> Đường kính: 22mm" ,
        "formPage": "Form_SP_Schneider_Safety.html"
    },
    {
        "id": "XB7NA42",
        "title": "Nút nhấn nhả Schneider XB7NA42, 22mm",
        "image": "Picture Schneider/XB7NA42.JPG",
        "sku": "XB7NA42",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Harmony-XB7_XB7NA42.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Tiếp điểm: N/C <br> Màu: Xanh đỏ <br> Đường kính: 22mm" ,
        "formPage": "Form_SP_Schneider_Safety.html"
    },
    // ----------------------------------------------------Relay-------------------------------------------------------------
    {
        "id": "RXM4LB2BD",
        "title": "Rơ le trung gian Schneider RXM4LB2BD 24Vdc 14 chân (có đèn)",
        "image": "Picture Schneider/RXM4LB2BD.JPG",
        "sku": "RXM4LB2BD",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Zelio-Relay_RXM4LB2BD.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Tiếp điểm: 4 C/O<br>Điện áp định mức: 24Vdc<br>Rơ le trung gian REXO có đèn chỉ thị<br>Dòng chịu tải: 3A<br>Tần số đóng ngắt tối đa: 1200 lần/ giờ<br>Tuổi thọ cơ khí: 10 triệu lần<br>Đáp ứng theo tiêu chuẩn: IEC/ EN60068-2-6, IEC/ EN60529, IEC/ EN60068-2-27" ,
        "formPage": "Form_SP_Schneider_AT.html"
    },
    {
        "id": "RXM4LB2P7",
        "title": "Rơ le trung gian Schneider RXM4LB2P7, 230Vac, 14 chân (có đèn)",
        "image": "Picture Schneider/RXM4LB2BD.JPG",
        "sku": "RXM4LB2P7",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Zelio-Relay_RXM4LB2P7.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Tiếp điểm: 4 C/O<br>Điện áp định mức: 230Vac<br>Rơ le trung gian REXO có đèn chỉ thị<br>Dòng chịu tải: 3A<br>Tần số đóng ngắt tối đa: 1200 lần/ giờ<br>Tuổi thọ cơ khí: 10 triệu lần<br>Đáp ứng theo tiêu chuẩn: IEC/ EN60068-2-6, IEC/ EN60529, IEC/ EN60068-2-27" ,
        "formPage": "Form_SP_Schneider_AT.html"
    },
    {
        "id": "RXM2LB1P7",
        "title": "Rơ le trung gian Schneider RXM2LB1P7, 230Vac, 8 chân",
        "image": "Picture Schneider/RXM4LB2BD.JPG",
        "sku": "RXM2LB1P7",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Zelio-Relay_RXM2LB1P7.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Tiếp điểm: 2 C/O<br>Điện áp định mức: 230Vac<br>Rơ le trung gian REXO có đèn chỉ thị<br>Dòng chịu tải: 5A<br>Tần số đóng ngắt tối đa: 1200 lần/ giờ<br>Tuổi thọ cơ khí: 10 triệu lần<br>Đáp ứng theo tiêu chuẩn: IEC/ EN60068-2-6, IEC/ EN60529, IEC/ EN60068-2-27" ,
        "formPage": "Form_SP_Schneider_AT.html"
    },
    {
        "id": "RXM2LB2BD",
        "title": "Rơ le trung gian Schneider RXM2LB2BD, 24Vdc, 8 chân (có đèn)",
        "image": "Picture Schneider/RXM4LB2BD.JPG",
        "sku": "RXM2LB2BD",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Zelio-Relay_RXM2LB2BD.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Tiếp điểm: 2 C/O <br>Điện áp định mức: 24Vdc <br>Rơ le trung gian REXO có đèn chỉ thị<br>Dòng chịu tải: 5A<br>Tần số đóng ngắt tối đa: 1200 lần/ giờ<br>Tuổi thọ cơ khí: 10 triệu lần<br>Đáp ứng theo tiêu chuẩn: IEC/ EN60068-2-6, IEC/ EN60529, IEC/ EN60068-2-27" ,
        "formPage": "Form_SP_Schneider_AT.html"
    },
    {
        "id": "RXM2AB2BD",
        "title": "Rơ le trung gian Schneider RXM2AB2BD 24Vdc 8 chân (có đèn)",
        "image": "Picture Schneider/RXM2AB2BD.JPG",
        "sku": "RXM2AB2BD",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Zelio-Relay_RXM2AB2BD.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Tiếp điểm: 2 C/O <br>Điện áp định mức: 24Vdc <br>Rơ le trung gian REXO có đèn chỉ thị<br>Dòng chịu tải: 5A<br>Tần số đóng ngắt tối đa: 1200 lần/ giờ<br>Tuổi thọ cơ khí: 10 triệu lần<br>Đáp ứng theo tiêu chuẩn: IEC/ EN60068-2-6, IEC/ EN60529, IEC/ EN60068-2-27" ,
        "formPage": "Form_SP_Schneider_AT.html"
    },
    {
        "id": "RXZE1M2C",
        "title": "Đế rơ le Schneider RXZE1M2C 8 chân dẹp nhỏ",
        "image": "Picture Schneider/RXZE1M2C.JPG",
        "sku": "RXZE1M2C",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Zelio-Relay_RXZE1M2C.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":" Đế 8 chân dẹp nhỏ. <br>Chịu dòng 7A <br>Bề rộng 22mm" ,
        "formPage": "Form_SP_Schneider_AT.html"
    },
    {
        "id": "RXZE1M4C",
        "title": "Đế rơ le Schneider RXZE1M4C 14 chân dẹp nhỏ",
        "image": "Picture Schneider/RXZE1M4C.JPG",
        "sku": "RXZE1M4C",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_Zelio-Relay_RXZE1M4C.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":" Đế 14 chân dẹp nhỏ. <br>Chịu dòng 6A <br>Bề rộng 22mm" ,
        "formPage": "Form_SP_Schneider_AT.html"
    },
    {
        "id": "LC1D09B7",
        "title": "Contactor Schneider LC1D09B7 9A 1NO+1NC 4kW 24VAC",
        "image": "Picture Schneider/LC1D09B7.JPG",
        "sku": "LC1D09B7",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_TeSys-Deca-contactors_LC1D09B7.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Khởi động từ Schneider dòng TeSys LC1D Series là sự kết hợp giữa độ bền của điện và máy cơ học, cung cấp đến một bộ tiếp xúc có độ tin cậy cao.<br>Trong hệ thống điều khiển TeSys LC1D được thiết kế động cơ tích hợp sao cho phù hợp với bất kỳ các loại ứng dụng khác nhau.<br>Khởi động từ Schneider dòng TeSys LC1D series được tối ưu đơn giản, nhưng vẫn đảm bảo tuân thủ đầy đủ các tiêu chuẩn của quốc tế.<br>Những tính năng ưu Việt của khởi động từ Schneider TeSys LC1D Series:<br>Có thể lắp bảng điều khiển bằng vít hoặc DIN Rail.<br>Các điểm tiếp xúc phụ được tích hợp sẵn cho khả năng chuyển đổi bổ sung.<br>Thiết bị đầu cuối đạt tiêu chuẩn IP20.<br>Bộ triệt tiêu diode giới hạn đỉnh hai chiều để bảo vệ cuộn dây." ,
        "formPage": "Form_SP_Schneider_AT.html"
    },   
    {
        "id": "LC1D09M7",
        "title": "Contactor Schneider LC1D09M7 9A 1NO+1NC 220V",
        "image": "Picture Schneider/LC1D09B7.JPG",
        "sku": "LC1D09M7",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_TeSys-Deca-contactors_LC1D09M7.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Khởi động từ Schneider dòng TeSys LC1D Series là sự kết hợp giữa độ bền của điện và máy cơ học, cung cấp đến một bộ tiếp xúc có độ tin cậy cao.<br>Trong hệ thống điều khiển TeSys LC1D được thiết kế động cơ tích hợp sao cho phù hợp với bất kỳ các loại ứng dụng khác nhau.<br>Khởi động từ Schneider dòng TeSys LC1D series được tối ưu đơn giản, nhưng vẫn đảm bảo tuân thủ đầy đủ các tiêu chuẩn của quốc tế.<br>Những tính năng ưu Việt của khởi động từ Schneider TeSys LC1D Series:<br>Có thể lắp bảng điều khiển bằng vít hoặc DIN Rail.<br>Các điểm tiếp xúc phụ được tích hợp sẵn cho khả năng chuyển đổi bổ sung.<br>Thiết bị đầu cuối đạt tiêu chuẩn IP20.<br>Bộ triệt tiêu diode giới hạn đỉnh hai chiều để bảo vệ cuộn dây." ,
        "formPage": "Form_SP_Schneider_AT.html"
    },  
    {
        "id": "LC1D18M7",
        "title": "Contactor Schneider LC1D18M7 18A 1NO+1NC 220V",
        "image": "Picture Schneider/LC1D18M7.JPG",
        "sku": "LC1D18M7",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_TeSys-Deca-contactors_LC1D18M7.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Khởi động từ Schneider dòng TeSys LC1D Series là sự kết hợp giữa độ bền của điện và máy cơ học, cung cấp đến một bộ tiếp xúc có độ tin cậy cao.<br>Trong hệ thống điều khiển TeSys LC1D được thiết kế động cơ tích hợp sao cho phù hợp với bất kỳ các loại ứng dụng khác nhau.<br>Khởi động từ Schneider dòng TeSys LC1D series được tối ưu đơn giản, nhưng vẫn đảm bảo tuân thủ đầy đủ các tiêu chuẩn của quốc tế.<br>Những tính năng ưu Việt của khởi động từ Schneider TeSys LC1D Series:<br>Có thể lắp bảng điều khiển bằng vít hoặc DIN Rail.<br>Các điểm tiếp xúc phụ được tích hợp sẵn cho khả năng chuyển đổi bổ sung.<br>Thiết bị đầu cuối đạt tiêu chuẩn IP20.<br>Bộ triệt tiêu diode giới hạn đỉnh hai chiều để bảo vệ cuộn dây." ,
        "formPage": "Form_SP_Schneider_AT.html"
    },  
    {
        "id": "LC1D12M7",
        "title": "Contactor Schneider LC1D12M7 12A 1NO+1NC 220V",
        "image": "Picture Schneider/LC1D12M7.JPG",
        "sku": "LC1D12M7",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_TeSys-Deca-contactors_LC1D12M7.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Khởi động từ Schneider dòng TeSys LC1D Series là sự kết hợp giữa độ bền của điện và máy cơ học, cung cấp đến một bộ tiếp xúc có độ tin cậy cao.<br>Trong hệ thống điều khiển TeSys LC1D được thiết kế động cơ tích hợp sao cho phù hợp với bất kỳ các loại ứng dụng khác nhau.<br>Khởi động từ Schneider dòng TeSys LC1D series được tối ưu đơn giản, nhưng vẫn đảm bảo tuân thủ đầy đủ các tiêu chuẩn của quốc tế.<br>Những tính năng ưu Việt của khởi động từ Schneider TeSys LC1D Series:<br>Có thể lắp bảng điều khiển bằng vít hoặc DIN Rail.<br>Các điểm tiếp xúc phụ được tích hợp sẵn cho khả năng chuyển đổi bổ sung.<br>Thiết bị đầu cuối đạt tiêu chuẩn IP20.<br>Bộ triệt tiêu diode giới hạn đỉnh hai chiều để bảo vệ cuộn dây." ,
        "formPage": "Form_SP_Schneider_AT.html"
    },
    {
        "id": "LC1D09BD",
        "title": "Contactor Schneider LC1D09BD 9A 1NO+1NC 4kW 24VDC",
        "image": "Picture Schneider/LC1D09B7.JPG",
        "sku": "LC1D09BD",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_TeSys-Deca-contactors_LC1D09BD.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Khởi động từ Schneider dòng TeSys LC1D Series là sự kết hợp giữa độ bền của điện và máy cơ học, cung cấp đến một bộ tiếp xúc có độ tin cậy cao.<br>Trong hệ thống điều khiển TeSys LC1D được thiết kế động cơ tích hợp sao cho phù hợp với bất kỳ các loại ứng dụng khác nhau.<br>Khởi động từ Schneider dòng TeSys LC1D series được tối ưu đơn giản, nhưng vẫn đảm bảo tuân thủ đầy đủ các tiêu chuẩn của quốc tế.<br>Những tính năng ưu Việt của khởi động từ Schneider TeSys LC1D Series:<br>Có thể lắp bảng điều khiển bằng vít hoặc DIN Rail.<br>Các điểm tiếp xúc phụ được tích hợp sẵn cho khả năng chuyển đổi bổ sung.<br>Thiết bị đầu cuối đạt tiêu chuẩn IP20.<br>Bộ triệt tiêu diode giới hạn đỉnh hai chiều để bảo vệ cuộn dây." ,
        "formPage": "Form_SP_Schneider_AT.html"
    },
    {
        "id": "GV2ME04",
        "title": "CB bảo vệ động cơ Schneider GV2ME04 (0.4-0.63A) 0.12kW",
        "image": "Picture Schneider/GV2ME04.JPG",
        "sku": "GV2ME04",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_TeSys-Deca-frame-2_GV2ME04.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Series: Schneider GV2ME <br>Dòng điện: 0.4A - 0.63A <br> Kích thước: 89x45x78.5mm(HxWxD) <br> Khối lượng	0.26kg" ,
        "formPage": "Form_SP_Schneider_AT.html"
    },
    {
        "id": "GV2ME07",
        "title": "CB bảo vệ động cơ Schneider GV2ME07 (1.6-2.5A) 0.75kW",
        "image": "Picture Schneider/GV2ME07.JPG",
        "sku": "GV2ME07",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_TeSys-Deca-frame-2_GV2ME07.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Series: Schneider GV2ME <br>Dòng điện: 1.6 - 2.5A <br> Kích thước: 89x45x78.5mm(HxWxD) <br> Khối lượng	0.26kg" ,
        "formPage": "Form_SP_Schneider_AT.html"
    },
    {
        "id": "GV2ME08",
        "title": "CB bảo vệ động cơ Schneider GV2ME08 (2.5-4A) 1.1kW",
        "image": "Picture Schneider/GV2ME08.JPG",
        "sku": "GV2ME08",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_TeSys-Deca-frame-2_GV2ME08.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Series: Schneider GV2ME <br>Dòng điện: 2.5 - 4A <br> Kích thước: 89x45x78.5mm(HxWxD) <br> Khối lượng	0.26kg" ,
        "formPage": "Form_SP_Schneider_AT.html"
    },
    {
        "id": "GV2ME06",
        "title": "CB bảo vệ động cơ Schneider GV2ME06 (1-1.6A) 0.37kW",
        "image": "Picture Schneider/GV2ME06.JPG",
        "sku": "GV2ME06",
        "manufacturer": "Schneider",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_Schneider/Schneider Electric_TeSys-Deca-frame-2_GV2ME06.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"Series: Schneider GV2ME <br>Dòng điện: 2.5 - 4A <br> Kích thước: 89x45x78.5mm(HxWxD) <br> Khối lượng	0.26kg" ,
        "formPage": "Form_SP_Schneider_AT.html"
    },






    // Add more products here
];

// Function to load product information based on product ID from URL
function loadProductInfo() {
    const urlParams = new URLSearchParams(window.location.search);
    const productId = urlParams.get('productId');

    const product = products.find(p => p.id === productId);

    if (product) {
        document.title = `${product.sku} - VietVuongAtech`;
        document.querySelector(".section-title").textContent = product.title;
        document.querySelector(".product-image img").src = product.image;
        document.querySelector(".product-description p:nth-child(1)").textContent = `SKU: ${product.sku}`;
        document.querySelector(".product-description p:nth-child(2)").textContent = `Nhà Sản Xuất: ${product.manufacturer}`;
        document.querySelector(".product-description p:nth-child(3)").textContent = `Chất Lượng: ${product.quality}`;
        document.querySelector(".product-description p:nth-child(4)").textContent = `Bảo Hành: ${product.warranty}`;
        document.querySelector(".product-description a").href = product.manual;
        document.querySelector(".product-description a").textContent = "Download PDF";
        document.querySelector(".product-description p:nth-child(6)").textContent = `Giá: ${product.price}`;
        document.querySelector(".infor-1").innerHTML = product.infor_1 || 'Thông tin không có sẵn';
        document.querySelector(".infor-2").innerHTML = product.infor_2 || 'Thông tin không có sẵn';
        document.querySelector(".infor-3").innerHTML = product.infor_3 
        document.querySelector(".infor-4").innerHTML = product.infor_4 
        
    } else {
        console.error('Product not found');
    }

}

function searchProducts() {
    const searchInput = document.getElementById('search-input').value.trim();
    const product = products.find(p => p.id.toLowerCase() === searchInput.toLowerCase());

    if (product) {
        // Redirect to the product page with the selected product ID
        window.location.href = `${product.formPage}?productId=${product.id}`;
    } else {
        alert('Sản phẩm không được tìm thấy');
    }
}

// Gọi hàm để tải thông tin sản phẩm khi trang tải
document.addEventListener("DOMContentLoaded", loadProductInfo);
