// Data: List of products
const products = [
    // ----------------------------------------------------------INVT-----------------------------------------------------------
    {
        "id": "GD20-0R7G-S2-BK",
        "title": "Biến tần INVT GD20-0R7G-S2-BK 0.75kW 1 Pha 220V",
        "image": "Picture_Invt/GD20-0R7G-S2-BK.png",
        "sku": "GD20-0R7G-S2-BK",
        "manufacturer": "INVT",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_INVT/GD20 Series VFD Manual_V1.9.pdf",
        "price": "Liên hệ (0896 449 884)",
        // "infor_1":"",
        // "infor_2":"",
    },

    {
        "id": "GD20-1R5G-S2",
        "title": "Biến tần INVT GD20-1R5G-S2 1.5kW 1 Pha 220V",
        "image": "Picture_Invt/GD20-0R7G-S2-BK.png",
        "sku": "GD20-1R5G-S2",
        "manufacturer": "INVT",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP_INVT/GD20 Series VFD Manual_V1.9.pdf",
        "price": "Liên hệ (0896 449 884)",
        // "infor_1":"",
        // "infor_2":"",
    },
    // ----------------------------------------------------------PLC S7-1200-----------------------------------------------------------
    {
        "id": "6ES7214-1AG40-0XB0",
        "title": "6ES7214-1AG40-0XB0 – Compact CPU 1214C DC/DC/DC S7-1200",
        "image": "Picture Siemens/S7-1200.png",
        "sku": "G6ES7214-1AG40-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/Catalogue_PLC_Siemens_S7_1200.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, CPU 1214C, COMPACT CPU, DC/DC/DC, ONBOARD I/O: 14 DI 24V DC; 10 DO 24 V DC; 2 AI 0 – 10V DC, POWER SUPPLY: DC 20.4 – 28.8 V DC, PROGRAM/DATA MEMORY: 100 KB.",
        "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
    },
    {
        "id": "6ES7212-1AE40-0XB0",
        "title": "6ES7212-1AE40-0XB0 – Compact CPU 1212C DC/DC/DC S7-1200",
        "image": "Picture Siemens/S7-1200.png",
        "sku": "6ES7212-1AE40-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/Catalogue_PLC_Siemens_S7_1200.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, CPU 1212C, COMPACT CPU, DC/DC/DC, ONBOARD I/O: 8 DI 24V DC; 6 DO 24 V DC; 2 AI 0 – 10V DC, POWER SUPPLY: DC 20.4 – 28.8 V DC, PROGRAM/DATA MEMORY: 75 KB.",
        "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
    },
    {
        "id": "6ES7211-1AE40-0XB0",
        "title": "6ES7211-1AE40-0XB0 – Compact CPU 1211C DC/DC/DC S7-1200",
        "image": "Picture Siemens/S7-1200.png",
        "sku": "6ES7211-1AE40-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/Catalogue_PLC_Siemens_S7_1200.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, CPU 1211C, COMPACT CPU, DC/DC/DC, ONBOARD I/O: 6 DI 24V DC; 4 DO 24 V DC; 2 AI 0 – 10V DC, POWER SUPPLY: DC 20.4 – 28.8 V DC, PROGRAM/DATA MEMORY: 50 KB",
        "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
    },
    {
        "id": "6ES7211-1BE40-0XB0",
        "title": "6ES7211-1BE40-0XB0 – Compact CPU 1211C AC/DC/relay S7-1200",
        "image": "Picture Siemens/S7-1200.png",
        "sku": "6ES7211-1BE40-0XB0 ",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/Catalogue_PLC_Siemens_S7_1200.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, CPU 1211C, COMPACT CPU, AC/DC/RELAY, ONBOARD I/O: 6 DI 24V DC; 4 DO RELAY 2A; 2 AI 0 – 10V DC, POWER SUPPLY: AC 85 – 264 V AC AT 47 – 63 HZ, PROGRAM/DATA MEMORY: 50 KB",
        "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
    },
    {
        "id": "6ES7214-1BG40-0XB0",
        "title": "6ES7214-1BG40-0XB0 – Compact CPU 1214C AC/DC/relay S7-1200",
        "image": "Picture Siemens/S7-1200.png",
        "sku": "6ES7214-1BG40-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/Catalogue_PLC_Siemens_S7_1200.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, CPU 1214C, COMPACT CPU, AC/DC/RLY, ONBOARD I/O: 14 DI 24V DC; 10 DO RELAY 2A; 2 AI 0 – 10V DC, POWER SUPPLY: AC 85 – 264 V AC AT 47 – 63 HZ, PROGRAM/DATA MEMORY: 100 KB.",
        "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
    },
    {
        "id": "6ES7212-1HE40-0XB0",
        "title": "6ES7212-1HE40-0XB0 – Compact CPU 1214C DC/DC/DC S7-1200",
        "image": "Picture Siemens/S7-1200.png",
        "sku": "6ES7212-1HE40-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/Catalogue_PLC_Siemens_S7_1200.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, CPU 1212C, COMPACT CPU, DC/DC/RLY, ONBOARD I/O: 8 DI 24V DC; 6 DO RELAY 2A; 2 AI 0 – 10V DC, POWER SUPPLY: DC 20.4 – 28.8 V DC, PROGRAM/DATA MEMORY: 75 KB.",
        "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
    },
    {
        "id": "6ES7212-1BE40-0XB0",
        "title": "6ES7212-1BE40-0XB0 – Compact CPU 1212C AC/DC/relay S7-1200",
        "image": "Picture Siemens/S7-1200.png",
        "sku": "6ES7212-1BE40-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/Catalogue_PLC_Siemens_S7_1200.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, CPU 1212C, COMPACT CPU, AC/DC/RLY, ONBOARD I/O: 8 DI 24V DC; 6 DO RELAY 2A; 2 AI 0 – 10V DC, POWER SUPPLY: AC 85 – 264 V AC AT 47 – 63 HZ, PROGRAM/DATA MEMORY: 75 KB.",
        "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
    },
    {
        "id": "6ES7211-1HE40-0XB0",
        "title": "6ES7211-1HE40-0XB0 – Compact CPU 1211C DC/DC/relay S7-1200",
        "image": "Picture Siemens/S7-1200.png",
        "sku": "6ES7211-1HE40-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/Catalogue_PLC_Siemens_S7_1200.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, CPU 1211C, COMPACT CPU, DC/DC/RELAY, ONBOARD I/O: 6 DI 24V DC; 4 DO RELAY 2A; 2 AI 0 – 10V DC, POWER SUPPLY: DC 20.4 – 28.8 V DC, PROGRAM/DATA MEMORY: 50 KB.",
        "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
    },
    {
        "id": "6ES7214-1HG40-0XB0",
        "title": "6ES7214-1HG40-0XB0 – Compact CPU 1214C DC/DC/relay S7-1200",
        "image": "Picture Siemens/S7-1200.png",
        "sku": "6ES7214-1HG40-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/Catalogue_PLC_Siemens_S7_1200.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, CPU 1214C, COMPACT CPU, DC/DC/RELAY, ONBOARD I/O: 14 DI 24V DC; 10 DO RELAY 2A; 2 AI 0 – 10V DC, POWER SUPPLY: DC 20.4 – 28.8 V DC, PROGRAM/DATA MEMORY: 100 KB.",
        "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
    },
    {
        "id": "6ES7215-1AG40-0XB0",
        "title": "6ES7215-1AG40-0XB0 – Compact CPU 1215C DC/DC/DC S7-1200",
        "image": "Picture Siemens/S7-1215.png",
        "sku": "6ES7215-1AG40-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/Catalogue_PLC_Siemens_S7_1200.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, CPU 1215C, COMPACT CPU, DC/DC/DC, 2 PROFINET PORT, ONBOARD I/O: 14 DI 24V DC; 10 DO 24V DC 0.5A 2 AI 0-10V DC, 2 AO 0-20MA DC, POWER SUPPLY: DC 20.4 – 28.8 V DC, PROGRAM/DATA MEMORY: 125 KB.",
        "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
    },
    {
        "id": "6ES7215-1BG40-0XB0",
        "title": "6ES7215-1BG40-0XB0 – Compact CPU 1215C AC/DC/relay S7-1200",
        "image": "Picture Siemens/S7-1215.png",
        "sku": "6ES7215-1BG40-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/Catalogue_PLC_Siemens_S7_1200.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, CPU 1215C, COMPACT CPU, AC/DC/RELAY, 2 PROFINET PORT, ONBOARD I/O: 14 DI 24V DC; 10 DO RELAY 2A, 2 AI 0-10V DC, 2 AO 0-20MA DC, POWER SUPPLY: AC 85 – 264 V AC AT 47 – 63 HZ, PROGRAM/DATA MEMORY: 125 KB.",
        "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
    },
    {
        "id": "6ES7215-1HG40-0XB0",
        "title": "6ES7215-1HG40-0XB0 – Compact CPU 1215C DC/DC/relay S7-1200",
        "image": "Picture Siemens/S7-1215.png",
        "sku": "6ES7215-1HG40-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/Catalogue_PLC_Siemens_S7_1200.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, CPU 1215C, COMPACT CPU, DC/DC/RELAY, 2 PROFINET PORT, ONBOARD I/O: 14 DI 24V DC; 10 DO RELAY 2A, 2 AI 0-10V DC, 2 AO 0-20MA DC, POWER SUPPLY: DC 20.4 – 28.8 V DC, PROGRAM/DATA MEMORY: 125 KB.",
        "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
    },
    {
        "id": "6ES7241-1CH30-1XB0",
        "title": "6ES7241-1CH30-1XB0 – Board truyền thông CB 1241 S7-1200",
        "image": "Picture Siemens/RS485.jpg",
        "sku": "6ES7241-1CH30-1XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/6ES72411CH301XB0_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, COMMUNICATION COMMUNICATION BOARD CB 1241, RS485, SCREW CONNECTOR SUPPORTS MESSAGE BASED FREEPORT.",
        // "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
    },
    {
        "id": "6ES7222-1BD30-0XB0",
        "title": "6ES7222-1BD30-0XB0 – Module SB 1222 4 DQ 24 VDC PLC S7-1200",
        "image": "Picture Siemens/SB-1222-digital-output-modules-4DQ-5VDC.png",
        "sku": "6ES7222-1BD30-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/6ES72221BD300XB0_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, DIGITAL OUTPUT SB 1222, 4DQ, 24VDC 200KHZ.",
        // "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
    },
    {
        "id": "6ES7232-4HA30-0XB0",
        "title": "6ES7232-4HA30-0XB0 – Module SB 1232 1AO SIMATIC S7-1200",
        "image": "Picture Siemens/6ES7232-4HA30-0XB0.jpg",
        "sku": "6ES7232-4HA30-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/6ES72324HA300XB0_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, ANALOG OUTPUT SB 1232, 1 AO, +/- 10VDC (12 BIT RES.) OR 0 – 20 MA (11 BIT RES).",
        // "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
    },
    {
        "id": "6ES7231-5PA30-0XB0",
        "title": "6ES7231-5PA30-0XB0 – Module SB 1231RTD 1 AI SIMATIC S7-1200",
        "image": "Picture Siemens/6ES7231-5PA30-0XB0.jpg",
        "sku": "6ES7231-5PA30-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/6ES72315PA300XB0_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, RTD INPUT, SB 1231 RTD, 1 AI RTD, 1 CHANNEL, PT 100 AND PT1000.",
        // "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
    },
    {
        "id": "6ES7223-3BD30-0XB0",
        "title": "6ES7223-3BD30-0XB0 – Module SB 1223 2 DI/2 DQ 24 VDC S7-1200",
        "image": "Picture Siemens/6ES7223-3BD30-0XB0.jpg",
        "sku": "6ES7223-3BD30-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/6ES72233BD300XB0_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, DIGITAL I/O SB 1223, 2DI/2DQ, 24VDC 200KHZ.",
        // "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
    },
    {
        "id": "6ES7222-1AD30-0XB0",
        "title": "6ES7222-1AD30-0XB0 – Module Digital output SB 1222 4 DQ S7-1200",
        "image": "Picture Siemens/6ES7222-1AD30-0XB0.jpg",
        "sku": "6ES7222-1AD30-0XB0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/6ES72221AD300XB0_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7-1200, DIGITAL OUTPUT SB 1222, 4DQ, 5VDC 200KHZ.",
        // "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
    },
    {
        "id": "6ES7954-8LC03-0AA0",
        "title": "6ES7954-8LC03-0AA0 – Thẻ nhớ cho S7-1×00 CPU/ Sinamics 4MB",
        "image": "Picture Siemens/6ES7954-8LC03-0AA0.jpg",
        "sku": "6ES7954-8LC03-0AA0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/6ES79548LC030AA0_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7, MEMORY CARD FOR S7-1X00 CPU/SINAMICS, 3,3 V FLASH, 4 MBYTE.",
        // "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
    },
    {
        "id": "6ES7954-8LC02-0AA0",
        "title": "6ES7954-8LC02-0AA0 – Thẻ nhớ cho S7-1×00 CPU/ Sinamics 4MB",
        "image": "Picture Siemens/6ES7954-8LC02-0AA0.jpg",
        "sku": "6ES7954-8LC02-0AA0",
        "manufacturer": "Siemens",
        "quality": "Mới 100%",
        "warranty": "Chính hãng",
        "manual": "SP Siemens/6ES79548LC020AA0_datasheet_en.pdf",
        "price": "Liên hệ (0896 449 884)",
        "infor_1":"SIMATIC S7, MEMORY CARD FOR S7-1X00 CPU/SINAMICS, 3,3 V FLASH, 4 MBYTE.",
        // "infor_2":"Tích hợp giao diện điều khiển I/O PROFINET.<br>Mô-đun truyền thông Master/Slave PROFIBUS DP.<br>Mô-đun GPRS để kết nối với mạng di động GSM/G.<br>Mô-đun LTE để liên lạc trong các mạng di động thế hệ thứ 4 (sự phát triển lâu dài).<br>Bộ xử lý truyền thông để kết nối với phần mềm TeleControl Server Basic điều khiển phần mềm trung tâm thông qua Ethernet, cũng như để giao tiếp an toàn qua mạng dựa trên IP.<br>Bộ xử lý truyền thông để kết nối trung tâm điều khiển cho các ứng dụng điều khiển từ xa.<br>RF120C để kết nối với hệ thống nhận dạng SIMATIC.<br>Mô-đun SM1278 để kết nối cảm biến IO-Link và thiết bị truyền động.<br>Kết nối point-to-point thông qua các mô-đun truyền thông hoặc bo mạch truyền thông.",
    },
    // Add more products here
];

// Function to load product information based on product ID from URL
function loadProductInfo() {
    const urlParams = new URLSearchParams(window.location.search);
    const productId = urlParams.get('productId');

    const product = products.find(p => p.id === productId);

    if (product) {
        document.querySelector(".section-title").textContent = product.title;
        document.querySelector(".product-image img").src = product.image;
        document.querySelector(".product-description p:nth-child(1)").textContent = `SKU: ${product.sku}`;
        document.querySelector(".product-description p:nth-child(2)").textContent = `Nhà Sản Xuất: ${product.manufacturer}`;
        document.querySelector(".product-description p:nth-child(3)").textContent = `Chất Lượng: ${product.quality}`;
        document.querySelector(".product-description p:nth-child(4)").textContent = `Bảo Hành: ${product.warranty}`;
        document.querySelector(".product-description a").href = product.manual;
        document.querySelector(".product-description a").textContent = "Download PDF";
        document.querySelector(".product-description p:nth-child(6)").textContent = `Giá: ${product.price}`;
        document.querySelector(".infor-1").innerHTML = product.infor_1 || 'Thông tin không có sẵn';
        document.querySelector(".infor-2").innerHTML = product.infor_2 || 'Thông tin không có sẵn';

        
    } else {
        console.error('Product not found');
    }
}

// Call the function to load the product info when the page loads
document.addEventListener("DOMContentLoaded", loadProductInfo);
